"""empty message

Revision ID: db9319e25d39
Revises: 06cf70ac2619
Create Date: 2019-05-30 16:55:35.476988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9319e25d39'
down_revision = '06cf70ac2619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zbhost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cmdb_hostid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'cabinet', 'idc', ['idc_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'server', 'cabinet', ['cab_id'], ['id'])
    op.create_foreign_key(None, 'switch', 'cabinet', ['cab_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'user', ['u_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'role', ['r_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'switch', type_='foreignkey')
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'cabinet', type_='foreignkey')
    op.drop_table('zbhost')
    # ### end Alembic commands ###
