"""empty message

Revision ID: dedd78c903eb
Revises: 35b3a3015357
Create Date: 2019-05-28 18:32:44.496835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dedd78c903eb'
down_revision = '35b3a3015357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cabinet', 'power',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'cabinet', 'idc', ['idc_id'], ['id'])
    op.alter_column('idc', 'rel_cabinet_num',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.create_foreign_key(None, 'role_o2m_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'role', ['r_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'user', ['u_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.alter_column('idc', 'rel_cabinet_num',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.drop_constraint(None, 'cabinet', type_='foreignkey')
    op.alter_column('cabinet', 'power',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
