"""empty message

Revision ID: f3bca92cf987
Revises: a2687576525a
Create Date: 2019-05-29 18:16:38.975144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bca92cf987'
down_revision = 'a2687576525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cabinet', 'idc', ['idc_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'server', 'cabinet', ['cab_id'], ['id'])
    op.create_foreign_key(None, 'switch', 'cabinet', ['cab_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'role', ['r_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'user', ['u_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'switch', type_='foreignkey')
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'cabinet', type_='foreignkey')
    # ### end Alembic commands ###
