"""empty message

Revision ID: fdd5a1d3f941
Revises: 6ebecd5ef7cd
Create Date: 2019-05-29 17:35:01.659652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd5a1d3f941'
down_revision = '6ebecd5ef7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('vm_status', sa.Integer(), nullable=True),
    sa.Column('st', sa.String(length=50), nullable=True),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('manufacturers', sa.String(length=100), nullable=True),
    sa.Column('server_type', sa.String(length=200), nullable=True),
    sa.Column('server_cpu', sa.String(length=200), nullable=True),
    sa.Column('os', sa.String(length=30), nullable=True),
    sa.Column('server_disk', sa.String(length=20), nullable=True),
    sa.Column('server_men', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=30), nullable=True),
    sa.Column('manufacture_date', sa.Integer(), nullable=True),
    sa.Column('check_update_time', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=30), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('cab_pos', sa.String(length=10), nullable=True),
    sa.Column('expire', sa.Integer(), nullable=True),
    sa.Column('supplier_phone', sa.String(length=20), nullable=True),
    sa.Column('server_up_time', sa.Integer(), nullable=True),
    sa.Column('server_purpose', sa.String(length=30), nullable=True),
    sa.Column('host', sa.Integer(), nullable=True),
    sa.Column('server_run', sa.String(length=30), nullable=True),
    sa.Column('host_status', sa.Integer(), nullable=True),
    sa.Column('host_models', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cabinet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'cabinet', 'idc', ['idc_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_o2m_permission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'switch', 'cabinet', ['cab_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'role', ['r_id'], ['id'])
    op.create_foreign_key(None, 'user_o2m_role', 'user', ['u_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'user_o2m_role', type_='foreignkey')
    op.drop_constraint(None, 'switch', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_o2m_permission', type_='foreignkey')
    op.drop_constraint(None, 'cabinet', type_='foreignkey')
    op.drop_table('server')
    # ### end Alembic commands ###
